/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isad.ehu;

import isad.ehu.controller.LiburuKud;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application {

    private Parent LiburuUI;
    private Parent mainUI;

    private Stage stage;

    private LiburuKud LiburuKud;
  //  private MainKud mainKud;

    @Override
    public void start(Stage primaryStage) throws Exception {

        stage = primaryStage;
        pantailakKargatu();

        stage.setTitle("Argazki Backup");
        stage.setScene(new Scene(mainUI, 450, 275));
        stage.show();
    }
    private void pantailakKargatu() throws IOException {

      /*  FXMLLoader loaderKautotu = new FXMLLoader(getClass().getResource("/main.fxml"));
        mainUI = (Parent) loaderKautotu.load();
        mainKud = loaderKautotu.getController();
        mainKud.setMainApp(this);

        FXMLLoader loaderMain = new FXMLLoader(getClass().getResource("/liburua.fxml"));
        LiburuUI = (Parent) loaderMain.load();
        LiburuKud = loaderMain.getController();
        LiburuKud.setMainApp(this);*/
    }
    public static void main(String[] args) {
        launch(args);
    }

    public void mainErakutsi() {
        stage.setScene(new Scene(mainUI));
        stage.show();
    }
}
